### ISSUE TITLE
raspi zero w support

### ISSUE THREAD

**Issue by IsaacNewton** [pimoroni/rp_usbdisplay#14]
Hello - followed this tutorial with the latest image of raspian on a working raspi zero.  When I go for the sudo depmod command I get this output:

depmod: ERROR: failed to load symbols from /lib/modules/4.4.50+/kernel/drivers/video/rp_usbdisplay.ko: Invalid argument

After that all is lost.  Do we have support for the raspi zero models yet?  I didn't see any disclaimers that the A processors weren't covered with this display.

thanks!
Ben

**Comment by Gadgetoid** [comment]
It absolutely should be covered, and I normally test this stuff on a Pi Zero W (my primary dev machine, for better or worse, 'cos it's portable!)

I'm not sure what's gone awry here, but it's possible I put the wrong kernel in the wrong place. I really need to get a DKMS package for this sorted! This method is bonkers.

**Comment by Gadgetoid** [comment]
Try the steps listed here: https://github.com/pimoroni/rp_usbdisplay/tree/master/dkms
