### ISSUE TITLE
Support for kernel 4.9.37-v7+

### ISSUE THREAD

**Issue by txk103** [pimoroni/rp_usbdisplay#15]
Howdy,

Is it possible to update the driver to kernel version 4.9.37-v7+ 

Regards
Tamas

**Comment by Gadgetoid** [comment]
See the DKMS package. I wont be building individual kernel modules anymore, since the DKMS package will do this far more robustly and with no ongoing maintenance.

https://github.com/pimoroni/rp_usbdisplay/tree/master/dkms

**Comment by txk103** [comment]
Cheers Gadgetoid, I should have looked around better. 

I have tried the DKMS approach but I'm still running into problems.
```

root@raspberrypi:/home/pi/rp_usbdisplay/dkms# sudo dpkg -i rp-usbdisplay-dkms_1.0_all.deb
(Reading database ... 64354 files and directories currently installed.)
Preparing to unpack rp-usbdisplay-dkms_1.0_all.deb ...

Uninstall Beginning
Module:  rp_usbdisplay
Version: 1.0
Kernel:  4.9.24-v7+ (armv7l)

Status: This module version was INACTIVE for this kernel.
depmod....(bad exit status: 1)

DKMS: uninstall completed.

Deleting module version: 1.0
completely from the DKMS tree.

Done.
Unpacking rp-usbdisplay-dkms (1.0) over (1.0) ...
Setting up rp-usbdisplay-dkms (1.0) ...

Loading tarball for rp_usbdisplay-1.0
Loading /var/lib/dkms/rp_usbdisplay/1.0/4.9.24-v7+/armv7l...

DKMS: ldtarball completed.

Creating symlink /var/lib/dkms/rp_usbdisplay/1.0/source ->
                 /usr/src/rp_usbdisplay-1.0

DKMS: add completed.
First Installation: checking all kernels...
dpkg: warning: version '*-*' has bad syntax: version number does not start with digit
It is likely that 4.9.37-v7+ belongs to a chroot's host
Building for architecture armhf
Module build for the currently running kernel was skipped since the
kernel source for this kernel does not seem to be installed.
```

Thank you,
Tamas

**Comment by Gadgetoid** [comment]
This isn't an issue I've come across with Raspbian, what system are you running?

**Comment by txk103** [comment]
Thanks, 

It is Raspian,  Jessie, however I mess around with a few things to try and get it to work. I will review and reply.

**Comment by DeathWreck** [comment]
when i wrote the code
**sudo apt install dkms raspberrypi-kernel-headers
sudo dpkg -i rp-usbdisplay-dkms_1.0_all.deb**
it said errors were encountered  whi;e processing

**Comment by DeathWreck** [comment]
and unable to locate pacage raspberrypi-kernals-headers

**Comment by DeathWreck** [comment]
and unable to locate pacage raspberrypi-kernals-headers

**Comment by psiconlab** [comment]
I'm having the same problem as txk103 on 4.1.13-v7+

**Comment by Gadgetoid** [comment]
Kernel headers should be available though apt, eg:

```
pi@raspberrypi:~ $ apt search raspberrypi-kernel-headers
Sorting... Done
Full Text Search... Done
raspberrypi-kernel-headers/testing 1.20170811-1 armhf
  Header files for the Raspberry Pi Linux kernel
```

**Comment by TheSyv** [comment]
Fairly new, to pi in general. I got the dkms to run following the readme and it completed with no issues, The screen still says its waiting for signal, am I missing something? 

I am working with the pi 3, Version 4.9.35-v7+
hoping you can assist me

**Comment by Gadgetoid** [comment]
Have you:
* rebooted since installing the kernel module
* loaded the rp_usbdisplay module and set it to start at boot in /etc/modules

If you read through ./install.sh you should see these steps: https://github.com/pimoroni/rp_usbdisplay/blob/master/install.sh

I need to update install.sh with support for the DKMS package, and automation of these steps but I haven't had a chance to do that yet.
