### ISSUE TITLE
Screen rotation

### ISSUE THREAD

**Issue by karihj** [pimoroni/rp_usbdisplay#16]
Thanks for the driver installer - works like a charm! I've tried to see if there is an easy way to rotate the robopeak display, but I can't seems to find any code that works. 

Is there a easy solution for this to rotate the screen to portrait mode?

**Comment by Gadgetoid** [comment]
Not that I'm aware of. A similar question has been unanswered by the developers since July 2016, unfortunately: https://github.com/robopeak/rpusbdisp/issues/14

I imagine you could accomplish it by modifying the driver, but that may not be the easy solution you're looking for!
