### ISSUE TITLE
raspberry w zero.. error "kernel is not supported."

### ISSUE THREAD

**Issue by sanghoyoon** [pimoroni/rp_usbdisplay#17]
Good morning. I would like to connect a 2.8 usb display to Raspberry pi zero w.
If there is a part I missed or something I do not know, please understand. because I am a beginner... Sorry..

I read your README and followed the installing part.
I cloned your project in downloads / and ran ./install.sh.

However, "Sorry. Current running kernel is not supported." Is displayed.

How do I use this display with Raspberry pi zero w?

**Comment by Gadgetoid** [comment]
Unfortunately I couldn't spare the time to keep building the modules manually.

You'll need to install dkms and use the dkms package, see here: https://github.com/pimoroni/rp_usbdisplay/tree/master/dkms

I'd recommend doing that in a Pi 3 if you have one available, and then transferring to a Zero. Or leave it overnight! The kernel-headers package is a bit huge.

**Comment by zaeval** [comment]
Hello, I use raspberry pi3 zero and I got same symptom.
So, I solved this problem how I downgrade my raspberry pi kernel to 4.9.24-v7+.

But I see only "Waiting for Signal" from display.

How can solve this problem??

**Comment by zaeval** [comment]
Oh, In raspberry pi3 it's working!
