### ISSUE TITLE
original repo unmaintained - use this instead?

### ISSUE THREAD

**Issue by yogo1212** [pimoroni/rp_usbdisplay#20]
The robopeak repo appears to be unmaintained with the last commit from 2015.

I've opened an issue on the original repo:
https://github.com/robopeak/rpusbdisp/issues/23

Would you accept pull requests for the code here?
Or maybe integrate the dkms module into one of the forks?
https://github.com/robopeak/rpusbdisp/network/members

**Comment by Gadgetoid** [comment]
I'm not sure I'm completely qualified to understand if any particular pull request will solve a given bug, and I don't necessarily have the time to test, but I'm certainly happy for you to raise PRs against this repository and also to give them due consideration.

If nothing else, it will serve as a big flag to lead people to your fork if you have a fix they require.
