### ISSUE TITLE
Low frame rate and input lag

### ISSUE THREAD

**Issue by zoomx19** [pimoroni/rp_usbdisplay#3]
I get a lot of input lag and frame rate issues

**Comment by Gadgetoid** [comment]
Unfortunately there's nothing I can do about that. This is a simple compile and repackage of the driver available here: https://github.com/robopeak/rpusbdisp

The framerate is, by default, fixed at 16fps, but you can change this when the module is loaded:

```
modprobe rp_usbdisplay fps=25
```
