### ISSUE TITLE
Wrong Module Version 4.4.21+ ARMv7 instead of ARMv6(?)

### ISSUE THREAD

**Issue by cmad157** [pimoroni/rp_usbdisplay#5]
'Night,
Just recently tested on a clean install of jessie lite (pi0) and was having issues installing the module, turns out that running modinfo in /4.4.21+/rp_usbdisplay.ko will have vermagic as ARMv7 instead of ARMv6 (like the 4.4.13+). I was trying to compile it myself to attach here, but alas I'm not having much luck.

> sudo modprobe rp_usbdisplay
> modprobe: ERROR: could not insert 'rp_usbdisplay': Exec format error
> 
> dmesg | tail -n1
> [ 1010.571466] rp_usbdisplay: version magic '4.4.14-v7+ SMP mod_unload modversions ARMv7 ' should be '4.4.21+ mod_unload modversions ARMv6 '

**Comment by Gadgetoid** [comment]
Drat! Not entirely sure how I borked that up. My build setup is in the office, I should be able to sort it out tomorrow morning.

**Comment by Gadgetoid** [comment]
I spent an entire morning bashing my head against my desk before I finally realized I had copied the kernel config to `config.txt` instead of `.config` and expected it to magically work. Fixed now, though. I've left my future self a note to save his sanity.
