### ISSUE TITLE
Kernel 4.4.34-v7+ support

### ISSUE THREAD

**Issue by bseyb** [pimoroni/rp_usbdisplay#6]
I would be awesome to get support for that kernel version, which is the current one atm.

**Comment by Gadgetoid** [comment]
Sorry, haven't had a chance to update it for a while.

I've skipped to 4.4.38-v7+ and 4.4.38+ which are the latest currently:

https://github.com/pimoroni/rp_usbdisplay/commit/75ac0a7c2ff3d64f5342bb3260f8fda3b17d4efd
https://github.com/pimoroni/rp_usbdisplay/commit/12db951c36443c8379f540a89c7bbe158aa41189

**Comment by bseyb** [comment]
Hey super thanks!
