### ISSUE TITLE
What format is the shoplogo.fb.gz file in?

### ISSUE THREAD

**Issue by johnhorner** [pimoroni/rp_usbdisplay#7]
As part of your install writes an image to the screen of the display with this line:

    zcat shoplogo.fb.gz > /dev/fb$FB

I would like to know what kind of image it is, and how I can send static images to the screen in a similar way. The .fb file extension is a bit mysterious and also the unix `file` command doesn't know what it is apart from "data".

**Comment by IrregularShed** [comment]
`file` is correct - it's data. It's raw data (gzipped) for the framebuffer, being copied into the framebuffer by the redirecting the output of `zcat` to it.

While there's nothing wrong with doing this, if you want to output plenty of images I'd suggest installing `fbi` - it's in the Raspbian repo. This is a framebuffer image viewer and handles plenty of file formats out of the box, so you wouldn't have to go creating raw bitmap images of whatever you want to display.

**Comment by johnhorner** [comment]
Thank you. I installed `fbi` but while the `zcat shoplogo.fb.gz > /dev/fb2` line worked from the command line, `fbi -d /dev/fb2 image.jpg` didn't, with the message:

    ioctl VT_GETSTATE: Invalid argument (not a linux console?)

any help with that will be gratefully received.

**Comment by johnhorner** [comment]
Answering my own question, this thread had the answer, the (undocumented) `-T` switch seems to solve that problem.

http://raspberrypi.stackexchange.com/questions/8922/how-do-i-display-images-without-starting-x11

**Comment by IrregularShed** [comment]
Ah, good work. (I'm away from home at the moment so was unable to follow up, sorry!)

**Comment by Gadgetoid** [comment]
The `shoplogo.fb.gz` image was actually generated by writing an image to framebuffer, and then dumping the result. I can't recall what I used, but it can't have been `fbi`- I can't for love nor money get it to work!

My approach would probably be to use only `png` images and write a quick and dirty Python utility for blitting images to the framebuffer. I might try to knock up an example for this repo if I find the time.
